#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${instanceId:${random.value}}
#
#spring:
#  application:
#    name: products-service
#  datasource:
#    url: jdbc:h2:file:~/products;AUTO_SERVER=true
#    username: root
#    password: pedro
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#
#axon:
#  eventhandling:
#    processors:
#      product-group:
#        mode: subscribing
#
#logging:
#  level:
#    org:
#      axonframework:
#        axonserver:
#          connector:
#            event:
#              axon:
#                AxonServerEventStore: DEBUG
#
#server:
#  error:
#    include-message: always
#    include-binding-errors: always